// <auto-generated />
using GreekRecruit.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreekRecruit.Migrations
{
    [DbContext(typeof(SqlDataContext))]
    [Migration("20250323144712_AddCommentTable")]
    partial class AddCommentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GreekRecruit.Models.PNM", b =>
                {
                    b.Property<int>("pnm_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pnm_id"));

                    b.Property<string>("pnm_comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pnm_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pnm_fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("pnm_gpa")
                        .HasColumnType("float");

                    b.Property<string>("pnm_instagramhandle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pnm_lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pnm_major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pnm_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("pnm_profilepicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("pnm_schoolyear")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pnm_id");

                    b.ToTable("PNMs");
                });

            modelBuilder.Entity("GreekRecruit.Models.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("user_id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
